# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx5120m -XX:MaxMetaspaceSize=1024m -XX:+UseG1GC -Dfile.encoding=UTF-8 -Djava.awt.headless=true
org.gradle.parallel=false
kotlin.code.style=official
android.nonTransitiveRClass=true
org.gradle.caching=false
org.gradle.configuration-cache=false
org.gradle.workers.max=1
googleServices.missing.passthrough=true
ksp.daemon.jvmargs=-Djava.awt.headless=true
kotlin.compiler.execution.strategy=in-process

